public class Input_Example_2 {
    public String lastName     {set;get;}
    public String firstName    {set;get;}
    public String city      {Set;get;}
    public String pancard    {set;get;}
    public String address1    {set;get;}
    public String address2    {set;get;}
    public String[] course    {set;get;}
    public String gender    {set;get;}
    public Input_Example_2(){
           course=new String[4];
    }
}